server:
  port: 8081
spring:
  application:
    name: userProvider
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:20000/eureka
